name: flutter_web_image_picker
description: A package designed for input images on web flutter.
version: 0.0.2
homepage: https://github.com/theoptimumcompany/flutter_web_image_picker

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebImagePicker
        fileName: flutter_web_image_picker.dart
